name: Build iOS IPA
on:
  workflow_dispatch:

jobs:
  build:
    name: Dong goi file IPA
    runs-on: macos-latest

    steps:
      - name: Lay ma nguon
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Fix loi quyen thuc thi
        run: |
          [ -f MapFileParser.sh ] && chmod +x MapFileParser.sh || true
          [ -f process_symbols.sh ] && chmod +x process_symbols.sh || true

      - name: Hack bypass loi thieu Plugin
        run: |
          # Kiểm tra xem file main.mm có tồn tại không trước khi tiêm
          if [ -f Classes/main.mm ]; then
            cat << 'EOF' >> Classes/main.mm
          extern "C" {
              int iOSPlugins__SMSsend() { return 0; }
              int iOSPlugins__Send() { return 0; }
              int iOSPlugins__back() { return 0; }
              int iOSPlugins__checkRotation() { return 0; }
              int iOSPlugins__getAgent() { return 0; }
              int iOSPlugins__getProvider() { return 0; }
              int iOSPlugins__purchaseItem() { return 0; }
              int iOSPlugins__unpause() { return 0; }
          }
          EOF
          else
            echo "Khong tim thay Classes/main.mm, bo qua inject!"
          fi

      - name: Build Xcode Project
        run: |
          # Dùng workspace thay vì project (Chuẩn Unity 2021+)
          xcodebuild -workspace Unity-iPhone.xcworkspace -scheme Unity-iPhone -configuration Release clean build \
          CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO \
          -sdk iphoneos \
          OTHER_LDFLAGS="-Wl,-undefined,dynamic_lookup" \
          CONFIGURATION_BUILD_DIR=build/Release-iphoneos

      - name: Dong goi thanh file .IPA
        run: |
          mkdir -p Payload
          # Copy file app vào thư mục Payload
          cp -r build/Release-iphoneos/*.app Payload/
          zip -r Avatar_iOS_V1.ipa Payload

      - name: Tra hang cho Chu tich
        uses: actions/upload-artifact@v4
        with:
          name: File-IPA-Hung-Le-Mmo
          path: Avatar_iOS_V1.ipa
