name: Build iOS IPA
on:
  workflow_dispatch:

jobs:
  build:
    name: Dong goi file IPA
    runs-on: macos-latest
    env:
      ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

    steps:
      - name: Lay ma nguon
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Hack bypass loi thieu Plugin
        run: |
          MAIN_MM=$(find . -name "main.mm" | head -n 1)
          if [ -n "$MAIN_MM" ]; then
            cat << 'EOF' >> "$MAIN_MM"
          extern "C" {
              int iOSPlugins__SMSsend() { return 0; }
              int iOSPlugins__Send() { return 0; }
              int iOSPlugins__back() { return 0; }
              int iOSPlugins__checkRotation() { return 0; }
              int iOSPlugins__getAgent() { return 0; }
              int iOSPlugins__getProvider() { return 0; }
              int iOSPlugins__purchaseItem() { return 0; }
              int iOSPlugins__unpause() { return 0; }
          }
          EOF
          fi

      - name: Build Xcode Project
        run: |
          PROJECT_FILE=$(find . -type d \( -name "*.xcworkspace" -o -name "*.xcodeproj" \) | head -n 1)
          if [ -z "$PROJECT_FILE" ]; then
            echo "Loi: Khong tim thay du an Xcode!"
            exit 1
          fi
          
          if [[ "$PROJECT_FILE" == *".xcworkspace" ]]; then
            CMD="-workspace $PROJECT_FILE -scheme Unity-iPhone"
          else
            CMD="-project $PROJECT_FILE -scheme Unity-iPhone"
          fi
          
          xcodebuild $CMD -configuration Release clean build \
          CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO \
          -sdk iphoneos \
          OTHER_LDFLAGS="-Wl,-undefined,dynamic_lookup" \
          CONFIGURATION_BUILD_DIR=build/Release-iphoneos

      - name: Dong goi thanh file .IPA
        run: |
          mkdir -p Payload
          APP_FILE=$(find build -name "*.app" | head -n 1)
          cp -r "$APP_FILE" Payload/
          zip -r Avatar_iOS_V1.ipa Payload

      - name: Tra hang cho Chu tich
        uses: actions/upload-artifact@v4
        with:
          name: File-IPA-Hung-Le-Mmo
          path: Avatar_iOS_V1.ipa
